- ItemList.py
- Settings.py
Added the option to (not) shuffle the Kokiri Sword for people who don't want to have the hassle of having to buy Deku Sticks all the time but still want to play with Open Forest
> Added the option to (not) shuffle the Kokiri Sword

- ItemList.py
- README.md
Update to the difficulty settings I proposed.
This makes the pools a bit more varied than 10 + 37 bluepees.
It also adds an explanation of the difficulty settings to the README.md (not sure where to position it, I just put it at the bottom).
> Update difficulty settings

- Main.py
- Settings.py
Simple version check, will need to change the hard coded URL later
I'm not too good with the gui, really this option should either not be there or on a seperate Dev panel. I can remove this if you want, but its here incase users want to disable it for Dev purposes, or they want to run it offline, until we get a proper Dev section
> Adding a version check

- Rules.py
For full compatibility with the new closed death mountain option.
> Logic Update for Lost Woods to Goron City

- Rom.py
- Settings.py
Added option for disabling background music. SFX and ambient sounds remain. ROM change:
```
0xB3CB18: ; in memory: 0x800C6BB8
-    or a0, t3, t4
+    or a0, r0, r0
```
> Disable Background Music option

- Rules.py
Key for key logic is possible here now that we have skullsanity.
> BotW GS Logic

- Patches.py
broke this accidentally when i implemented custom colors, oops
> fixed random choice colors

- Rules.py
Couple of extra has('Bomb Bag')'s hanging around. Changed them to Bombs, not that it matters...
> has('Bomb Bag') to has_bombs() & Fix Bombchu Shop

- Utils.py
> fix default output not using realpath

- Settings.py
A lot of people in the Discord were expressing confusion over the current tooltip.
> Made some tooltips clearer

- Patches.py
> Setting default targetting to hold no longer overrides saved setting

- Rules.py
Decided not to split DC into regions because I don't think they would have helped very much.
A few more changes to other areas were noticed.
Changed my mind about a couple things.
> MQ Shops Logic Update Part 2

- MQ.py
- Main.py
- Rom.py
* dmadata helper functions moved out of MQ.py into Rom.py, some functions renamed for better consistency
* read_rom now class function, accepts file argument instead of stream
* Compressor, decompressor calls simplified
> MQ.py and Rom.py refactoring

- HintList.py
Found a grammar error in HintList.
> Hint-Grammar-Fix

- Patches.py
- Settings.py
settings.py failed to update the list without manual adding. streamlined so only changes to patches.py is needed as well as splitting HP and Navi SFX as some SFX shouldn't be in both. Added a bunch of new SFX as well. Might not be as clean as it should be, if it needs cleaning up feel free.
> Update SFX to be easier to add to

- ItemList.py
- Patches.py
- README.html
- README.md
- Settings.py
This option works with Enhanced Maps/Compasses and gives the player all the maps and compasses from the start.
> Added 'Start With' option to Shuffle Maps/Compasses

- Main.py
there was a typo that caused the option to generate all patch files from the same world
> fix multi world generation

- SettingsList.py
Also changes 'default' to the default value, not the GUI text of the default value.
> Invert Key/Value for Setting_Widget parameter 'choices'

- Fill.py
- Hints.py
- World.py
Ganon now tells you the location of your Light Arrows, not the location of some Light Arrows that may exist in your world.
> Fix Multi-World Light Arrows Hint

- Gui.py
- Patches.py
- SettingsList.py
Still planning on adding more sound hooks
> Add Custom Ocarina SFX

- SettingsList.py
- data/World/Bottom of the Well.json
- data/World/Deku Tree.json
- data/World/Dodongos Cavern.json
- data/World/Fire Temple MQ.json
- data/World/Fire Temple.json
- data/World/Forest Temple MQ.json
- data/World/Forest Temple.json
- data/World/Ganons Castle MQ.json
- data/World/Gerudo Training Grounds MQ.json
- data/World/Overworld.json
- data/World/Spirit Temple MQ.json
- data/World/Spirit Temple.json
Sorry for the absurdly inflated line count.
I didn't update the readme to reflect these new options.
Reordering the trick list is a task for another time.
> Split Various Advanced Tricks

- Patches.py
- SettingsList.py
- Sounds.py
Add new file `Sounds.py`, revising Patches and SettingsList to fit.
> Refactor sfx settings

- ASM/src/rainbow_bridge.asm
- Fill.py
- Gui.py
- ItemPool.py
- Main.py
Just a few unrelated miscellaneous changes.
> Minor Changes

- Fill.py
I am not sure if this fix makes all the proper assumptions as to the data used, but it seems to work and should be somewhat close to the intended balancing.
>  Fix Multiworld Mixed Dungeons

- Sounds.py
> Add none option back into sfx

- Cosmetics.py
- ItemPool.py
- Settings.py
- SettingsList.py
Enhanced Maps/Compasses is now defaulted to off. Junk Ice Traps is now defaulted to normal. Moved Junk Ice Traps to above Item Pool.
> Minor Settings Changes

- Patches.py
Fixes https://github.com/TestRunnerSRL/OoT-Randomizer/issues/412
> Fixes an error "Item" is not iterable when placing a fake ice trap in a shop that looks like a bottle

- Fill.py
- data/World/Water Temple MQ.json
- data/World/Water Temple.json
Add more detailed comments so that other newcomers don't make the same mistakes as I did in #421 and #423.
> Add more detailed comments

- Patches.py
It pains me to do this
~~Fixes~~ Closes TestRunnerSRL/OoT-Randomizer#433
> Remove shit from Zelda

- ItemPool.py
- Patches.py
- SettingsList.py
- data/World/Overworld.json
> Option to have king zora moved from the start

- Cosmetics.py
- SettingsList.py
Used "random" before - makes setting all sfx to random easier for the web patcher.
> Update bg music and ocarina to use "random-choice"

- Fill.py
- World.py
Also changes some other exceptions for consistency.
> Fix Multiworld Mixed Dungeons

- Gui.py
- Settings.py
Also a minor refactor of update_seed to allow it to generate a new random seed if needed.
> Generate Random Seed if Seed is Empty String

- Cosmetics.py
- Main.py
This allows for cosmetic options that have known locations to be patched even when not all options can be. It also sets up a simple framework to allow for future versions to be backwards compatible with older patches.
> Better Cosmetic Version Handling

- LocationList.py
- Main.py
- Messages.py
- Patches.py
- README.md
- SettingsList.py
- World.py
Also changes the spoken item name to "mysterious item".
> Scrub Shuffle: Update scrub messages with correct price.

- Messages.py
- Patches.py
> Remove the extra line break (vanilla 1.0 bug)

- Patches.py
> Prevent chest in MQ Spirit from being moved

- Fill.py
Some improvements to the fill code implementation. No function change, but cleans up the code in prep for entrance rando. No entrance specific code is added.
> Fill code minor refactoring

- Cosmetics.py
- Sounds.py
This doesn't actually change anything functionally, but allows for easily adding/removing sounds from certain categories or even adding new sounds to the list and many categories all at once.
> Refactoring sound lists to make future changes easier

- Patches.py
- SettingsList.py
- State.py
- World.py
Self-explanatory, this adds a setting in the Other tab to choose your starting age.
Starting as adult is compatible with closed Door of Time but not with closed Forest.
> Add starting age option (child, adult or random)

- README.md
Starting the changelog for 5.0 so its easier to manage
> Start Changelog for 5.0

- Hints.py
- OoTRandomizer.py
> Fix tournament hint distribution with multiple disabled 'always' locations.

- LocationList.py
Looks like this got accidentally changed in another merge
> change "Minigame" back to "Minigames"

- data/World/Water Temple.json
> Require hookshot for water temple Map chest

- State.py
- Use map and filter when appropriate, as they're generally faster.
- Remove defunct __getattr__.
- Some reordering of test branches that all require the same thing.
- Readability adjustments.
> Small improvements to State.

- data/Glitched World/Water Temple.json
Fixed Glitched Water Temple key requirements to not be dependant on keysanity.
> Fixed Glitched Water Key Requirements

- README.md
Nothing else was added since my last update :)
> Changelog update: Move options to proper changelog section

- Patches.py
- SettingsList.py
Adds fast chickens option
Adds Checkbox in --> Timesavers
Redone the whole thing because it was messed up after i tried things.
Now it should be fine.
> Fast Chickens + Checkbox

- Patches.py
an unrelated bug that broke on this line made me realize this code could be written a little better
> make exit_table generation more robust

- EntranceShuffle.py
- tests/entrance.sav
I made some changes to the entrance shuffling algorithm to be more efficient and handle more situations. It should fail less often now and be slightly faster now, and it's also a bit cleaner overall.
Also removed events from being guaranteed reachable when ALR is enabled, since those aren't actual item locations which the player should always have access to. For instance, this will avoid things like child access to water temple being guaranteed.
> Improve the ER algorithm to be more performant and robust

- State.py
- data/Glitched World/Overworld.json
Fixed Zora River Front missing hint area and put stealing Epona back in logic.
> Fix some Glitched Logic issues

- README.md
Fixed some grammatical errors and made it more consistent.
> Grammatical error and consistency fixes

- State.py
This requires a weapons check for child
> Fix fast gerudo logic

- SettingsList.py
- data/Glitched World/Fire Temple MQ.json
- data/World/Fire Temple MQ.json
- data/World/Fire Temple.json
- data/World/Jabu Jabus Belly.json
- data/World/Water Temple MQ.json
- data/World/Water Temple.json
Ironsless water and Adult Jabu tricks.
Few little bits of logic tightening in water. See patch by patch for notes.
> Tricks & Logic Tweaks (mostly water temple)

- data/World/Bottom of the Well MQ.json
- data/World/Ice Cavern MQ.json
Fixing a couple of bugs relating to MQ ER.
For the Ice Cavern fix, this is the entrance to the Compass Room:
> MQ ER logic fixes

- SettingsList.py
- data/World/Overworld.json
Dampe 2 as child is very time restrictive and should be a trick instead.
> Make Dampe 2 as child a trick

- State.py
Fixes the ER algorithm testing access to Links House for child... as adult.
> Pass the age from as_age to with_age.

- Main.py
Until now the entrance playthrough listed all shuffled entrances and in which playthrough sphere they became accessible, but most of those entrances weren't actually ever important for the playthrough. So it wasn't very useful and added quite a lot of noise in the spoiler for not much gain.
Now, with those changes, only the shuffled entrances used by the playthrough to complete the seed are listed. This uses exactly the same pattern as the item playthrough uses by reducing all entrance spheres in reverse order until we only have the required entrances for the playthrough.
When shuffling many entrances like in full ER, this does increase generation time by a significant amount (a few seconds) since reducing spheres is a long process, for both items and entrances, but I believe it's worth …
> Improve the ER entrance playthrough to only show required entrances

- Entrance.py
- EntranceShuffle.py
- Hints.py
- Item.py
- Location.py
- Playthrough.py
- RuleParser.py
- Rules.py
- Unittest.py
*  Evaluates constants in rules parsing.
*  Removes some unnecessary function calls in Playthrough.
*  Tests hint access to gossip stones by using event items.
*  Merges some setup into common functions.
> Various improvements to rules

- Cosmetics.py
- Music.py
- Rom.py
Aligns audioseq and the sequences within audioseq to 0x10 to fix crashes and silent tracks on console.
> Music shuffle console compatibility

- Music.py
- data/Music/.gitignore
- data/Music/README.md
Allows users to sort custom sequences into sub-directories however they see fit
> Read Music folder recursively

- README.md
Update Changelog to v4.15.53; clean up hyperlinks to Changelog sections of the Readme.
> another changelog update

- Hints.py
This confused reviewers (because its plain wrong).
> Fix misleading comment

- SettingsList.py
> Minor "Dungeons Have One Major Item" Tooltip Fix

- Hints.py
> Fix duplicate/overlapping hints

- Hints.py
After a long discussion, some felt that the hint for dorf to say his own BK contents is completely useless.  With new rulesets of GGJ and noIM/WW being official, and both having trials skips, this hint is now reachable even with trials on.  It's also in logic to reach dorf without LA and trials on in glitch logic.
> Dorf always hints LA

- data/World/Fire Temple MQ.json
> Fire Temple MQ Chest Near Boss requires tunic/ftr.

- Main.py
- Settings.py
> Omit disabled settings from spoiler output.

- SettingsList.py
- data/World/Overworld.json
People have been asking for this for potential removal from weekly settings.  Also aligns this with using a flower in DMT as both being a trick.
> trick-ify goron city pot with flower

- SettingsList.py
- World.py
- data/LogicHelpers.json
- data/World/Overworld.json
Rules associated with PR #966, taken from #946
> Require Stone of Agony for hidden grottos

- Plandomizer.py
Resolves
`    raise FillError('Not all locations have an item.')
Fill.FillError: Not all locations have an item.`
When placing shop buy items in plandos.
> Plando: Handle shop Buy items

- SaveContext.py
> Fix child equipped tunic when starting as adult

- Fill.py
- Plandomizer.py
- SaveContext.py
Fixes Ice Traps added by plando and `starting_items` not having a model assigned. Also properly updates the `item_pool` record for an item added by `starting_items`.
> A lot of Plando fixes

- Plandomizer.py
~~Depends on: #990~~ Dependency has been merged
~~[Cleaner diff based on dependency](https://github.com/flagrama/OoT-Randomizer/compare/plando-tests...flagrama:refactor-pattern_dict_items?expand=1)~~
~~Hopefully this makes it more readable than the mess that was there before.~~
> Plando: Refactor pattern dict items

- SettingsList.py
We have quite a lot of tricks, so I thought we could probably make use of this system we already have in place.
Just gave all the tricks some initial tags according to their location, MQ, and GS pretty much.
> Filter tags for list of tricks

- ItemPool.py
- LocationList.py
- data/Glitched World/Gerudo Training Grounds MQ.json
- data/Glitched World/Gerudo Training Grounds.json
- data/World/Fire Temple MQ.json
- data/World/Gerudo Training Grounds MQ.json
- data/World/Gerudo Training Grounds.json
Image of this location: https://discordapp.com/channels/274180765816848384/274180765816848384/759026662293110805
I've repurposed the existing "Wall Switch Fairy" for convenience.
> Added a new fairy location to GTG (MQ) logic

- Cosmetics.py
The purpose of this change is to ensure the font inside button icons is always readable, notably when used as a note or in the pause menu. It does mean some of the darker colors will never be selected, but I think it's more important to keep the game accessible and playable no matter what.
> Prevent randomized button colors from being too dark

- Settings.py
This feels hacky as shit and I don't like it but it works for now.
> Fix 'Randomize Main Rule Settings'
