TestRunnerSRL/OoT-Randomizer

Main.py
`output_dir` is scoped specifically in the `if not settings.suppress_rom`, which borks creating spoiler logs only without a ROM.  Moving this outside of the `if not` block allows creating logs without a ROM.
=> output_dir scope change allows spoiler log w/o ROM

README.md
Felt like reading the README again, found some typos and that it still considered bombchu logic always on.
=> Fix some typos in the readme and correct bombchu logic being an option

Main.py
Compress for Mac and Linux take only one argument and it automatically appends `-comp` to the compressed ROM.  The previous argument does not respect `output_dir`, looking for the uncompressed output ROM in the base dir causing a file not found error if an output directory is specified.  This change uses `rom_path` as to respect the user's set `output_dir`.
=> Fixes Compress Args for Mac/Linux

ItemList.py, Settings.py
The Ocarina of Time Randomizer feels very easy in terms of combat because you naturally run across a lot of health upgrades and defensive items like Nayru's Love, double defense, and double magic.
To counteract this, the following options are added:
- normal: Default items
- hard: Double defense, double magic, and all 8 heart containers are removed
- very_hard: Double defense, double magic, Nayru's Love, and all health upgrades are removed
The hard difficulty still leaves the heart pieces in the pool, so the player can gain up to 12 hearts total, likely a few less though. It also doesn't remove NL, but still takes away double magic so it can't be spammed for multiple minutes of invulnerability.
The very_hard difficulty just takes it all away, meaning the player will stay at 3 hearts …
=> Difficulty settings

Main.py, Settings.py
This changes the Compress ROM option to be selected by default. Anyone who needs the uncompressed rom probably already knows what they're doing. It also deletes the uncompressed rom from the output directory after compressing it. The uncompressed rom is useless for most people and 99% of the time it's opened, it's user error.
=> Compress ROM by default

Rom.py
This PR fixes the issue of Zelda's Letter reverting to a Chicken, even after talking to Impa.
The vanilla game checks that Zelda's Lullaby is in your inventory when saving and resetting after receiving Zelda's Letter. If it isn't, the letter reverts to a Chicken and the "talked to Zelda in courtyard" flag resets (preventing learning Saria's Song as well). The randomizer changes this to check for the song you learned from Impa instead, by simply changing the song that it checks for.
Songsanity changes the check "song learned from Impa is in the inventory" to "talked to Impa in the courtyard". Obviously this is because Impa will not necessarily teach a song. However, the change is reverted to check for "song learned from Impa" if Songsanity is not enabled. The value telling the code which …
=> Fix for reverting Zelda's Letter

Settings.py
default `world_count` and `player_num` arguments to a value of `1` to match the Gui and to continue to make it possible to generate a seed with only the `rom` argument
=> Add default values for co-op settings

HintList.py, Hints.py
Gerudo Fortress keys have a unique item type `FortressSmallKey` that is different from the generic `SmallKey` type. This item type lacks an entry in the hints table, causing the hint to fall back to the entry for `useless`. We add an entry to the table to properly account for this case.
Here is an example seed/settings combination that exhibits the issue:
* Settings: RJDU9VUBAAUB
* Seed: BZURYLQVEG
In this seed, there is a Gerudo Fortress key in the Fire Temple which is granted a hint. Before this change, the hint reads `something worthless`. After this change, it reads `a get out of jail free card`.
Before:
```sh
$ python3.6 -m pdb OoTRandomizer.py --rom './Output/ZOOTDEC.z64' --settings_string RJDU9VUBAAUB --seed BZURYLQVEG --create_spoiler
> …
```
=> Fix incorrect hints for fortress keys

BaseClasses.py, Fill.py, ItemList.py, Settings.py
Reworked dungeon item shuffling to be more consistent, as per #37. Notable effects:
- Combined two settings flags, "Remove Maps and Compasses" and "Keysanity", into a new combobox.
- Maps and compasses are no longer replaced by arbitrary junk when moved from their dungeon (this means there is no longer any option that changes the total set of items that exist, other than Gerudo key skip turning unnecessary keys into hearts)
- Keysanity behavior is preserved as before
To my knowledge we were already changing text for keys/maps/compasses even when they were left in the proper dungeon, but it's possible that I missed something there. Someone with more experience with the codebase should make sure nothing broke with the progression system, but it seems correct from what I can tell.
=> rework dungeon item shuffling

Rules.py
Dins to destroy flowers on the other side of rocks has precedent now with the LW to Goron City exit. Also there's a chance something similar will be coming up in MQ as well...
You can actually just light these flowers with a deku stick by jump-slashing them through the rocks. But that seemed a stretch for logic inclusion...
=> BotW Map Chest Logic

Regions.py, Rules.py
Now requires 1 less key than before.
It was equivalent back before the freestanding key was randomized, and saved 1 line of code.
=> Logic Fix - Shadow GS

BaseClasses.py, Regions.py, Rules.py
For all three of these fixes, songs were using "has" and that was changed to "can_play".
Biggoron was also missing the full access requirement for Zora's Domain, which could potentially include Hover Boots now, instead of just Zelda's Lullaby.
Since the original creation of the PR it was realized that Biggoron had further issues in the case of the Claim Check item. Since that item does not need to be delivered on a timer, Bolero (along with Hookshot, Hover Boots, or Magic Bean) can be used to reach Biggoron instead of needing one of the requirements that won't expire the timer.
And it was noticed that the Shadow Temple Freestanding Key was in logic with bombchus. While that's definitely possible, it was not intentional.
And somebody got an impossible seed because the Death Mountain Crater …
=> More Logic Fixes

Rom.py, Settings.py
This patch adds an option to randomize the background music. If selected, all the background music (music that loops) will be randomized among itself. The tracks that are randomized are at the bottom of Rom.py. 
Also updated the Disable Background Music option to fully mute all background music (same tracks that get randomized). If Disable and Randomize are both chosen, disable takes priority, as you would probably expect.
=> Randomize Background Music

Rom.py
Seems to be some weirdness with the file select music that I didn't run into while testing initially. It uses the same track as the fairy fountain but a different instrument set pointer. I removed the file select track from the randomization as I'm pretty sure it's unused, and just write the fairy fountain instrument pointer over the file select one.
=> Randomized music bug fix

ItemList.py
Due to the change to the meaning of world.keysanity, gerudo fortress keys were being world shuffled instead of left alone, when small keys are removed.
=> Bug Fix for removing keys with Gerudo Fortress

Settings.py
Caught a typo in the Maps & Compasses tooltip and a missing space.
=> Tooltip-Typo-Fix

Rules.py
You need all the keys to use the lower door.
If you put keys behind that door and never unlock it, you'll get key locked.
=> Fire Temple Keysanity Logic Fix

BaseClasses.py, Main.py
I sort-of kind-of redid the alg for generating the spoilers and the hints.
Please verify that it works correctly!
There's one dirty little section of code in baseclasses, where I had to go way out of my way to match up two copies of what should be the same object (and the old code suggests they were believed to actually be the same object) but they were not. (Previously it didn't matter that this code didn't do anything because even if it did something it wouldn't have done anything.) Please find a cleaner way to fix this little bit of nonsense? (The break was needed because it would sometimes find the same location twice. Is that normal?)
The method remove_locations is no longer in use as far as I could see?
The false branch of can_beat_game might no longer be used as well, haven't …
=> Bug Fixes for Spoilers/Hints

OoTRandomizer.py
This prevents the randomizer from crashing when run offline.
=> Import required HTTP errors

ItemList.py, Settings.py
This PR adds a setting called `logic_earliest_adult_trade` that allows to set which item is the earliest in the adult trade sequence that will show up.
It mainly aims to give users a setting to reduce variance between seeds where Biggoron is required and one either has to do barely anything or almost the entire adult trading sequence.
I'm not sure what the default setting of this should be, so I just set it to Pocket Egg to mimic the seeds that were created before the option got added.
Created a bunch of test seeds and it worked as expected.
Since I'm a dummy and have no clue how to use command line arguments for the rando, I'm not sure if the help would look good.
=> added adult_trade_option

Items.py, Rules.py
Adding various calls to can_use, mostly.
But some bug fixes as well.
Bug Fixes:
- King Dodongo (Vanilla & MQ)
- King Dodongo Heart (Vanilla & MQ)
- Lake Hylia Freestanding PoH
- Goron Shop
- GS Desert Colossus Hill
- Desert Colossus Grotto
- Dodongos Cavern MQ Torch Puzzle Room Chest
Changed my mind on killing GS Well MQ Basement with a pot.
For the comments I removed about the quirks, as well as a list of some things I decided not to put into logic, see the bottom of this paste:
https://pastebin.com/4h0XpQih
=> Logic Fixes Part 3

Rules.py
Breaks up lengthy rules onto multiple lines, using 120 characters per line as a rough guide but allowing some lines to exceed that length if it would hurt readability to break them up further.
The Rules.py file is one of the most interesting parts of this codebase, from the perspective of a casual OoT player with an interest in randomizers. However, it can be prohibitively difficult to follow the logic of some of the rules due to the great number of logical groupings that are present. The Spirit Temple logic was always a prime example of this, in my mind. With these changes, I hope to make Rules.py more approachable, as well as reducing any chance of logical bugs caused by poorly grouped checks.
I am not an experienced Python programmer, so I am not particularly familiar with Python code …
=> Rules Line Breaks

Patches.py
Sets the flag that you got caught by the guards in Gerudo Fortress. Prevents short cutscene from playing.
This flag is shared with the flag for the tower collapse cs at the end of the game, but that cutscene is skipped already anyway.
=> Skip "caught by gerudo" cutscene

.gitignore, ItemList.py, Patches.py, README.html, README.md, Rules.py, SettingsList.py
Difficulty is now about item distribution in general, whereas OHKO should be possible with any general item distribution difficulty. It makes sense for the two to be separate options now.
In the future this option could be used to set a damage multiplier or something, but implementing that is outside of my abilities.
=>  Separate 'OHKO' mode from Difficulty

Settings.py
Fixes a ValueError that causes a settings reset when a new setting is added or setting options are changed.
=> Don't disregard settings.sav when a new setting with options is added.

Gui.py, Main.py
Fixes the unintended modification of the filename of the spoiler file when generating a patch file. Also allows single .zpf files to be used to generate a ROM.
=> Fix Patch File Naming

Settings.py
This is useful to quickly understand what settings any given settings string holds, as well as converting a list of settings to a settings string without invoking the rest of the randomizer code.
=> Add option for converting settings to a string and back

HintList.py, Hints.py, ItemList.py, Main.py, SettingsList.py
A few minor changes.
First, fixes the file name of multi-world patch files by adding an underscore between the seed and the W#P# part of the file name.
Second, reinstates Ice Traps back into OHKO mode. Whatever softlock issue these had in the past is seemingly resolved at this point.
Finally, adds "Useless" as a hint distribution option, which is nothing but junk hints.
=> Miscellaneous Changes

BaseClasses.py, Main.py
Gossip Stone hints for all players are now included in the spoiler log. As a result, the player number is no longer included in the filename for multi-world spoilers.
Also added [W#] next to locations in multi-world spoilers to more easily Ctrl+F the correct location/world.
Filename logic in general cleaned up a bit.
Before/After spoiler logs: http://runs.live/OoT_CRUA4ACEJSABAL3A4AAM4RHLBC_MS4BYD6FGZ_W2_Spoiler.zip
=> Multi-World Spoiler Fixes

Patches.py
Since the keys changed, all dungeons would show as Normal, even if they are actually Master Quest.
=> Fix Master Quest in Dungeon Info Screen

Item.py, Main.py
When a location was copied, it set its item's world to the world of the location. This is bad if there are more than one world!
=> Fix Multi-World Playthroughs

Gui.py, SettingsList.py
The first commit keeps the Settings String updated in the GUI as the World Count changes.
The second commit fixes the Create Spoiler Log dependency and adds one for Player Number so that those settings are greyed out in the GUI when they do not affect anything.
=> Minor GUI Settings Fixes

Main.py, Spoiler.py
Two changes designed to account for the fact that a long, long settings string should not be in a filename, and yet it is nice to be able to keep a log of what settings were used to generate a particular seed for reference or troubleshooting / debugging purposes.
=> Create Settings Log is Spoiler Log is Disabled / Use Partial Hash of Settings String for Filenames

Gui.py, data/presets_default.json
The idea being that people can distribute their presets as a separate file and the user can just drop it into their randomizer directory instead of doing something awful like manually editing JSON.
=>  Allow "presets_xyz.sav" files that contain locked presets.

Fill.py, ItemPool.py, Patches.py, Rules.py, SettingsList.py
This branch adds the following settings:
1. "Start with max rupees" - The player begins the game with 99 rupees.
2. "Start with Deku equipment" - The player begins the game with 10 Deku sticks and 20 Deku nuts (which normally can be bought or obtained by killing enemies in the starting area). Additionally, if playing without shopsanity, the player begins with a Deku shield equipped (which can also be bought).
3. "Start with fast travel" - The player begins the game with the Prelude of Light and Serenade of Water songs learned (but no ocarina) and the Farore's Wind spell (but no magic meter). These three items increase Link's mobility around the map, but don't actually unlock any new items or areas.
The "start with fast travel" option required some minor rework of the ItemPool logic (to …
=> Add convenience settings for faster start

Rules.py, data/World/Overworld.json
I think this is required because in Rules.py only the requirements for meds/ad/vanilla get set. So if it "defaults" to meds and open doesn't overwrite it with `True`, there could never be early progression in GC for open bridge, right?
=> Fix open bridge logic

data/World/Deku Tree.json, data/World/Fire Temple MQ.json, data/World/Overworld.json
1. Added means of dealing with the Skulltula to reach the basement chest in Deku Tree.
2. There was a lava run in Fire Temple MQ that couldn't be reasonably done on 3 hearts in quad damage.
3. There was a lava run in Goron City that couldn't be reasonably done on 3 hearts in quad damage.
4. The scarecrow route into central crater can't be done in time with 3 hearts without Goron Tunic. It also takes a full heart of fall damage and so can't be done on ohko or in 3 hearts with quad damage, without a fairy or Nayru's.
=> Logic Fixes

Rules.py
Forest Temple MQ has a chest that can be only viable for a small key, so we need to make sure the boss key isn't placed there in those cases.
=> Fix MQ Forest Temple Key Placement (Issue #354)

ItemPool.py, Patches.py, SettingsList.py
I find it frustrating to open chests containing purple or larger rupees and be unable to hold them, plus wallets are kind of an annoying gate to attaining items. This option starts Link with the largest wallet.
Also if combined with "Start with Max rupees" it accounts for the increased capacity.
=> Add option for starting with Tycoon wallet

SettingsList.py
A bunch of small changes to the tooltips of shuffle options in main rules to keep them consistent.
This is purely just a bit of housekeeping, but I did notice that there were a few inconsistencies with how the tooltips were phrased.
Some described what happened if the option was disabled, and some described what happened if the option was enabled. For consistency sake, I've rewritten them to all describe what happens when the option is enabled, as well as rewriting them to be a bit clearer.
=> Consistency in tooltip descriptions

LocationList.py
This is probably harmless due to bosses being excluded from hints, but
worth fixing for the future.
=> Fix Phantom Ganon location to Forest

Main.py
Especially with regards to the web patcher where people need to carry around their files, some users WILL rename their archive files to something different. This makes it more difficult to lookup the right patch file directly just based on the player id as you can not rely on the zpfz file name to determine the archive file name. Furthermore the current GUI flat out breaks if that happens and tells the user the player id is incorrect, which is confusing. 
This change makes the archive file names consistent just based on the player id
=> Make zpfz archive file names predictable

Messages.py
The default error message was being shuffled into the text pool. This _should be enough_ to fix it.
Closes TestRunnerSRL#516
=> Exempt text id error from text shuffle, some cleanup

Hints.py
There was a period missing at the end of the hint generated when trials are random and all trials are skipped ("They say that Sheik dispelled the barrier around Ganon's Tower").
=> Add missing period in 0 trials hint when trial amount is random

Cosmetics.py
Made a small mistake that went untested on my sword trails, the transparencies for vanilla sword trails were a bit screwed up. These small changes fix that.
=> Fixing white sword trails

Fill.py
The shop items were not accounted for it the total locations to fill,
however ther are accounted for incremental progress. Fix by adding
shops to the total. This avoids the progress bar from jumping
backwards.
=> Prevent fill progress overshoot

Gui.py, Main.py, SettingsList.py
Also allows generation of cosmetics log when creating patch files. For multiworld, these cosmetic logs will be embedded in the patch file archive.
=> Add way to not repatch cosmetics when applying patch file.

LocationList.py, SettingsList.py, data/World/Jabu Jabus Belly MQ.json, data/World/Overworld.json
2 cows lacked can_play(Eponas_Song) in their logic. Also removed the extra cow location that was added by accident. Also fixes the tooltip for Shuffle Gerudo Card.
=> Cow Shuffle Logic Fixes

data/World/Bottom of the Well.json, data/World/Deku Tree MQ.json, data/World/Deku Tree.json, data/World/Fire Temple.json, data/World/Forest Temple.json, data/World/Ice Cavern.json, data/World/Overworld.json, data/World/Shadow Temple MQ.json, data/World/Shadow Temple.json
Remove assumptions from dungeons about the overworld path taken to reach dungeon entrances. Few misc changes for the ice cavern blue_fire spec and the deku tree gossip stones.
Regression tested with 5000 all-sanity generations as having no impact to current (non-ER) logic.
=> Remove Assumptions from Dungeon Logic - small stuff

data/World/Water Temple.json
No hook, irons or tunic assumptions. Also prepare for the definition
of a trick to longshot the torch without irons which is logically ok
in ER (as water temple might not be at the lake anymore).
Regression tested with 5000 all-sanity seeds as no logic diff to current (non-ER).
=> Remove entry assumptions from water temple

SettingsList.py, State.py, data/World/Dodongos Cavern.json, data/World/Fire Temple MQ.json, data/World/Fire Temple.json, data/World/Forest Temple.json, data/World/Overworld.json, data/World/Spirit Temple MQ.json, data/World/Spirit Temple.json
Changes:
- Fixed bug with can_finish_adult_trades not considering open gerudo fortress.
- Added tricks:
1. Adult Meadow Access without Saria's or Minuet
2. Reach Volvagia without Hover Boots or Pillar
3. Diving in the Lab without Gold Scale
4. Deliver Eye Drops with Bolero of Fire
5. Wasteland Crossing without Hover Boots or Longshot
6. Desert Colossus Hill GS with Hookshot
7. Dodongo's Cavern Scarecrow GS with Armos Statue
8. Kakariko Tower GS with Jump Slash
9. Lake Hylia Lab Wall GS with Jump Slash
10. Spirit Temple MQ Lower Adult without Fire Arrows
11. Spirit Temple Map Chest with Bow
12. Spirit Temple Sun Block Room Chest with Bow
=> Add Tricks Part 2

Main.py
Command line logger output was incorrectly saying `Created settings log at: spoiler.json` instead of `Created spoiler log at: spoiler.json`.
=> Fix logger output when creating a spoiler file

Entrance.py, Fill.py, Location.py, Region.py, RuleParser.py, Rules.py, State.py, data/World/Deku Tree MQ.json, data/World/Deku Tree.json, data/World/Dodongos Cavern MQ.json, data/World/Dodongos Cavern.json, data/World/Forest Temple MQ.json, data/World/Forest Temple.json, data/World/Ice Cavern MQ.json, data/World/Ice Cavern.json, data/World/Overworld.json, data/World/Spirit Temple MQ.json, data/World/Spirit Temple.json
This PR is a preparation for the "Start as Adult" and Entrance Shuffle options.
It's mostly an internal change and shouldn't affect the logic other than fixing it in some instances.
Although it was regression tested on a lot of seeds and settings, some changes might be incorrect so it would be good if this was reviewed by those able to do so.
Below is a compiled summary of the commit messages for an explanation of the changes:
**1. Rework child/adult logic by adding an age parameter to can_reach**
Split reachability by age:
- can_reach is essentially redefined as can_reach(spot, 'child') OR can_reach(spot, 'adult').
- The old is_adult condition that checks if the state has master sword is renamed to can_become_adult.
- 2 new state conditions are available: is_child and is_adult. When …
=> Rework child/adult logic by adding an age parameter to can_reach

Patches.py, SaveContext.py
Child items weren't automatically equipped when starting as adult and going back child for the first time, this is now fixed.
=> Fix default equipped child items when starting as adult

data/World/Gerudo Training Grounds.json, data/World/Ice Cavern.json
These are local checks so should be as_either_here
No effect to current logic, may impact ER
=> misc dungeons: Clarify as_either to as_either_here

State.py, data/World/Water Temple MQ.json
Logic changes related to scarecrow song:
- Fix a scarecrow check in Water Temple MQ not actually testing if the player could have scarecrow song.
- Add has_ocarina to the recently added has_scarecrow_song method to avoid potential issues with it.
=> Fix some minor Scarecrow Song logic issues

Entrance.py, Location.py, Main.py, OoTRandomizer.py, Playthrough.py, State.py, data/World/Overworld.json
This implements a BFS simulation of a playthrough, tracking the regions accessed in each sphere and caching those regions and the exits to new regions that can't yet be taken, rather than use the can_reach inward DFS (inward because it starts at the goal location and searches backward until it finds an accessed region). This cuts generation time down nearly 50% depending on settings, and hopefully it's easier to understand. There may be more room for the Fill algorithm to take advantage of the new Playthrough caching, but the majority of time spent is in create_playthrough so that was what I was focusing on.
Experimental times on my laptop:
- Accessible, count=10:  33s -> 19s
- Accessible, worlds=5: 2m16s -> 1m10s
- Sanity (ocarina/egg/songs/cows/scrubs/shops/tokens/keys/maps+compasses): …
=> Faster collect_locations and playthrough generation

Playthrough.py
I suspect tokensanity results in child collecting all of its locations in an initial pass before keys are placed, triggering the observed issue.
Another fix may come later, where the fill algorithm uses playthroughs to reuse the caches there.
=> Fix accidentally skipping adult in some cases.

data/World/Overworld.json
The setup for water with hookshot and scale is a little on the harsh
side. Kick it out of logic as this has already come up in the support
channels with suggestion by support it should be out. Could be trick
level in the future.
=> Require longshot to open water with no boots

data/World/Water Temple.json
NOTE: Not urgent - seeds are still fully valid without this fix.
This puts water temple middle level properly in logic for child.
=> Correct sticks usage

LocationList.py
Since the cow in Link's House is the reward for a minigame, it should be added to the Minigames category in the exclusion lists.
=> Add link's house cow to minigames exclusion category

Hints.py
The tournament hint distribution was failing if any of the hint categories didn't have enough hints to generate the fixed number of hint types. For example, if only one area in the seed was barren, it couldn't generate 2 different barren hints so it ended up failing. It could also not generate entrance hints when entrances weren't shuffled so it would fail in this case for every seed.
With this it will only fail if there aren't enough valid random hints to fill the gap caused by hints missing in other types.
=> Fix tournament hint distribution to only fail when out of random hints

data/World/Overworld.json
Shadow Temple entrance could end up with the Kokiri Forest hint area because of the warp song entrance, instead of the expected graveyard hint area, this is now fixed.
=> Fix shadow entrance not using the proper hint area

EntranceShuffle.py
In case the entrance shuffle failed once, the retry would throw an error when generating the rollback because it used regions instead of entrances.
=> Fix entrance shuffle retry

Main.py, Rules.py
- Wallet requirements in shopsanity no longer override existing location access rules.
- Entrance shuffling now accounts for vanilla shop location rules. This prevents some placement issues like having the Goron Shop/Zora Shop potentially placed behind a child only entrance even if shopsanity is off and ALR is enabled.
=> Fix some small issues related to shop access rules

data/World/Overworld.json
Vanilla Bottom of the Well isn't affected by this logic issue, because it checks for being child internally. 
But Botw MQ doesn't check for that currently, which means the logic wrongly considered that adult could access Botw MQ locations.
=> Fix botw being logically accessible as adult in non entrance shuffle

Plandomizer.py
Variable is `player_id`, not `player_world.id` - this caused quite a bit of confusion while testing plando
=> fix wrong identifier in plando fill logic

Cosmetics.py
It was still setting it to ocarina
=> Fix Lost Woods minigame to use the correct instrument

EntranceShuffle.py, ItemList.py, ItemPool.py, Playthrough.py, Rules.py, State.py, data/Glitched World/Overworld.json, data/World/Overworld.json
Mostly internal logic changes, shouldn't change anything other than making generation slightly faster and fixing some playthrough issues in the spoiler.
- Change Link's House and Temple of Time save&quit points to be children of a common Root region.
- Update the playthrough algorithm to support a unique common root, and remove assumptions about Beyond Door of Time always having a path to Link's House.
- Change the Master Sword Pedestal event item to "Time Travel" to make the playthrough consistent between child and adult start.
I had to make some changes to the new playthrough algorithm so I'm curious to hear what @Zannick thinks about it and if he knows a better way to handle having a common root. I think this is good enough as it is but there might be some possible improvements.
=> Use a unique root in logic and fix playthrough inconsistencies

RuleParser.py, data/Glitched World/Deku Tree.json, data/Glitched World/Forest Temple.json, data/Glitched World/Ganons Castle.json, data/Glitched World/Overworld.json, data/Glitched World/Spirit Temple MQ.json, data/Glitched World/Spirit Temple.json, data/Glitched World/Water Temple.json, data/World/Deku Tree.json, data/World/Spirit Temple MQ.json, data/World/Spirit Temple.json
The rule parser was accepting unknown conditions instead of throwing an error, which resulted in conditions being incorrectly defaulted to True. 
I changed that behavior so the parser throws an exception in this case and fixed a bunch of typos in the current logic that were being incorrectly parsed, in both glitchless and glitched logic (@dotzo).
=> Fix some logic typos and add an exception thrown when rule parsing fails

World.py
This resulted in the time of day setting property being randomized again every World copy when the starting time of day option was set to "random".
=> Fix starting time of day not being copied in the World instance

Main.py
Glitched logic currently doesn't support some settings like MQ dungeons and Entrance Rando, so No Logic should default to the Glitchless world structure to avoid issues when using it with MQ and ER.
=> Change No Logic to default to Glitchless world data instead of Glitched

data/World/Overworld.json
Zora River Front itself didn't have any hint area so it defaulted to Hyrule Field instead of Zora's River.
=> Fix Zora River Front Region not using the correct hint area

Playthrough.py, State.py
- Remove old location cache on reset.
- In State.can_reach, use Playthrough cache as positive-only cache for now.
This fixes issues where a playthrough could have never-required items (multiple Buy Bombchu, Ice Arrows, etc) or fail to reach Ganon.
=> Fix Playthrough issues.

DungeonList.py
In No Logic, the overworld was recently changed to default to glitchless data files, but dungeons weren't updated to match that so some issues could still appear in MQ or ER settings.
=> Fix No Logic not using the correct data files

SettingsList.py
I think this got lost in the SettingsList.py cleanup.
=> Make 'World Count' Affect Settings String

data/World/Fire Temple.json
Interim Support Information:
Only affects closed door of time or Non-ALR settings. Also has a ground jump
workaround.
I had this at one stage but lost it if code refactoring. This is definately
tested as needing adult height.
=> Fix child fire big lava room

Patches.py, SettingsList.py, data/World/Overworld.json
Walking into adult Kak for a free dungeon is OP, and the SoS is
hugely devauled in ER due to open adult well. Fix it by consistently
requiring SoS to enter the well for both adult and child.
=> Balance fix - require SoS for ER well entry

Main.py
When reducing playthrough spheres, there is no point testing if the game is still beatable after uncollecting an item that can't ever be required, i.e. if a duplicate of that item is already obtained and it's not progressive. So we can just skip the test in this case, which improves performance by a decent amount.
=> Improve generation speed by skipping some useless playthrough checks

Patches.py
Make the well blocking stone conditional on the well being drained.
The stone is still unconditionally absent for child.
This shuts down the strange logic of getting well access with Irons
instead of SoS.
=> Stop Iron boots access to Adult well

Patches.py
Rewrote how scene exits are updated. It now builds a lookup table containing the address of all indexes within the exit lists across all playable scene setups, instead of iterating over the scene setups for every modified index.
Renamed write_entrance -> copy_entrance_record
Fixed a bug where hopping over the gate blocked by Ingo would take you to the vanilla location
=> Fix some issues with entrance randomizer

Settings.py, SettingsList.py
Added a "force junk" option to the Detailed Logic tab. Function will force blue rupees at the excluded locations, utilizing the Plandomizer routine. If songsanity is off, the function skips over song locations, allowing them to be handled by the fill algorithm. If a distribution file is loaded, that file takes precedent (as it's assumed the user will have defined which locations should be junk).
=> Force Junk at Excluded Locations

EntranceShuffle.py, Playthrough.py, State.py
Some time of day cases weren't handled correctly and the Entrance Shuffle algorithm wasn't always guaranteeing time passing access from the beginning of the seed. This should now be fixed, and situations like #672 shouldn't happen anymore.
Also cleaned up a bit of the ER code and some comments that weren't completely accurate.
=> Fix time of day logic issues and cleanup some ER code

World.py
Nayru's Love may be required to reach the Goron City grotto which could contain a useful grotto in ER regardless of other settings, so it shouldn't be excluded from required items in that case. Fixes #668.
=> Fix Nayrus Love being incorrectly foolish in grotto ER

Patches.py
Both Owl Flying cutscenes are now almost completely skipped.
=> Speed up Owl Flying cutscenes

Fill.py, Main.py, OoTRandomizer.py, Unittest.py
Adds a global retry to seed generation, fixes fuzzer settings output to be run reproducibly (the settings string is for the originally provided settings, NOT the randomly selected settings, and adds some better debug information to the log (like the full list of settings).
Also skips attempting to fill locations marked minor-only for major items, which helps diagnose placement issues from one_item_per_dungeon.
=> Global retry and debugging changes

data/Glitched World/Overworld.json, data/World/Overworld.json
Fixes some potentially major logic issues that could result in broken Overworld ER or Glitched seeds:
- Change Gerudo Fortress Gate to not be considered openable as child. This broke when the recent event items were added. Applies to Glitched Logic as well.
- Change Lake Hylia Control to logically require a sword. Boomerang and Slingshot do not trigger a text box so they don't work.
- Change shield and PoH graves to require night time as child, since they can't be opened during the day because of the kid there.
- Change some LLR locations to properly require day time.
=> Fix some ER and Glitched logic issues

Patches.py
This prevents the OoT cutscene (and probably some other cutscenes) from being changed in ER due to sharing the same entrance index as Impa's escorts.
=> Fix Impa escort changes in ER to not affect other cutscenes

ItemPool.py, State.py
Salesman now provides only Bombchus item, which with chus in logic
allows purchasing chus from shops and playing Bombchu Bowling, but
does not itself count as a renewable source. With chus not in logic,
Bombchus item has no effect.
Given that has_bombchus is thus impossible without a Bomb Bag
with chus not in logic, short-circuit the explosives check.
=> Nerf Bombchu Salesman. (Fixes #688)

Plandomizer.py
Pushing junk to disabled locations causes an error when a disabled location is locked due to not being included in the seed (eg. a scrub when scrubsanity is off). This restores previous functionality ignoring the excess disabled locations.
=> Don't fail on disabling locked locations.

Hints.py
Considering the hint distribution is called 'very strong', I don't see why there should be a limitation on how many barren dungeons can get hinted at (if one even gets multiple barren dungeons).
=> Multiple barren dungeons in very strong hints

EntranceShuffle.py
Fixed the entrance index for that grotto which was incorrect after the recent grave/grotto changes and caused it to load as a 2 scrubs grotto instead of a fairy fountain. Fixes #711.
=> Fix Zoras Domain Storms Grotto loading as the wrong grotto

Patches.py, data/World/Ice Cavern.json
Enable child to learn Serenade from the Ice Cavern. This is consistent
with requiem and also bring another child learnable song into play
that is not weir egg locked (makes closed DoT much more interesting).
Hacked the en_xc (Sheik) actor to always consider Link an adult. en_xc
is removed from the actor table for child for most instances. (e.g.
Sheik is simply absent from Child crater by actor lists). Sheik at ToT
is unaffected (by testing) and all others are cutscenes except for
requiem where we want Sheik to work for child anyway. So make the
change unconditional on location.
=> Enable child serenade

Fill.py, Main.py, Unittest.py, tests/ac-mq.sav, tests/multiworld.sav, tests/plentiful.sav
Fix a warning on logging.warn.
Unittest changes:
- Add unittests for disabled locations.
- Fix a bug in multiworld woth tests where all players were P1.
- Remove nut, stick, and shield refills from "max-once" consideration.
- Given that, canonicalizing "max-once" items isn't necessary.
- Changes to unittest settings files.
=> Apply distribution to all worlds (fixes #716).

data/World/Overworld.json
This was missing an adult check now that Dampe's Grave can sometimes be accessed by child in grotto ER (child isn't high enough to climb the ledge behind the time blocks).
=> Fix Dampe's Grave -> Windmill logic in ER

Patches.py
This never affected logic but the lake state was always shared between child and adult in ER, even with the "child may drain lake hylia" option disabled. I think this was left from back when the child option wasn't a thing, and it was bound to dungeon ER instead.
It will now only be applied when the corresponding option is enabled.
=> Fix child lake control patching being always applied in ER

data/World/Water Temple.json
I think this should've been 6 (-1 is 5) ever since the lock was removed? Because that door was locked behind Central Pillar access, so the actual key requirements for Central Pillar shouldn't change (but therefore should change in the logic file because of the fake "7th" key).
=> Fix Water Temple key requirements

Patches.py
The time travel routine normally unsets the swordless flag when going adult so we also have to manually do it when starting as adult.
=> Fix Adult Start issues with sword getting unequipped in some cases

Patches.py
Removed the scene restriction on warp songs in some relevant places:
- Gerudo Training Grounds
- Inside Ganon's Castle (Trials)
- Dampe's Grave / Windmill
- Treasure Chest Minigame
Also removed the restriction on Farore's Wind in dungeons where it was originally forbidden:
- Gerudo Training Grounds
- Inside Ganon's Castle (Trials)
Note: The Treasure Chest Minigame case is a bit special because allowing warp songs requires allowing Ocarina usage, which can be a problem due to Sun's Song being usable to cheat your way through the minigame. To avoid this abuse, Sun's Song is now explicitly forbidden in the Chest Minigame scene.
=> Allow Warp Songs and Farore's Wind in additional places

Patches.py
In vanilla, when you zone out of spirit onto the hands of the colossus
then jump down and re-enter spirit from the front door, the temporary
switch flags are preserved. This is bad for ER, as it means flicking
switches in spirit, will cause switches to also flick in the dungeon
on-spirit if you jump off the hands.
Fix it by always clearing the temp flags zoning into spirit from the
front door when dungeon ER is enabled. Zoning out to a hand then back
in will still preserve the flags as per vanilla, only the front door
is changed.
This works by clearing the temp preservation flag on the sprit entry
polygon data.
=> Fix spirit temp flags ER bug

State.py, data/World/Overworld.json
Made Goron City logic (for a child fire source and stopping Link the Goron) a bit simpler by using event locations more efficiently.
=> Simplify Goron City logic with event locations

SettingsList.py, data/World/Overworld.json
Adds a logic trick to remove the unintuitive ability to pass through some visually apparent one-way collisions from default logic. A casual player couldn't guess that those collisions don't actually exist when coming from one side so I think going through them belongs to a trick.
This is only relevant for starting as adult and for ER, but can be quite major in some situations. Especially passing through the Kakariko Gate as child can logically open up a lot of things in Overworld ER.
Note: I'm not 100% sure about the right wording on the trick itself, or where it belongs on the list.
@r0bd0g Let me know if this is fine or if anything should be changed.
=> Make passing through visible one-way collisions a logic trick

data/World/Ice Cavern.json, data/World/Overworld.json
We generally agreed that using explosives to kill wolfos is too tough to be in default glitchless logic, so I updated the logic to not include them. This wasn't relevant before overworld ER because having explosives meant you could always get sticks from Goron City, so it never came up as an issue.
Also fixed a minor bug with the wolfos grotto chest where can_child_attack was used but that includes the Boomerang which doesn't actually damage them.
=> Fix wolfos child weapon checks in ER

Messages.py, Patches.py, Rom.py
* Expand nes_message_data_static to it's maximum size before overwriting the staff messages and removed the broken spillover to jpn_message_data_static. If the extra space is still not enough, let me know.
* Greatly simplified Message.size() and Message.write() by implementing Message.transform(), which modifies the message's text_code list before writing back. 
* Text shuffle now accepts the message list, instead of waiting for all dialogs to be written back and then read from rom again
=> Messages.py clean-ups

ItemPool.py, LocationList.py, data/World/Overworld.json
Playing the song of storms near a planted bean spawns 3 fairies that can be stored in a bottle, and this can be relevant in some ER scenarios.
Note: I plan on adding a part about the many ways to get fairies in the ER logic quirks on the wiki. This will be included as well since it's not necessarily common knowledge.
=> Add relevant fairy locations for growing a planted bean

Hints.py, Messages.py, TextBox.py
Mostly fixes #749.
Splits out control code parsing into a static method so that it can be used to more intelligently replace line/box breaks with spaces when re-wrapping text for multiworld.
Removed a block of code from TextBox.py that seemed to serve no other purpose than to mangle the Magic Beans text.
=> Fix Text Wrapping Issues

Patches.py, SettingsList.py, State.py
Renamed the starting times of day to be more universal and updated the times they set based on in-game times and intention of the times of day, i.e. sunrise is the frame after skulltulas despawn and sunset is the frame skulltulas spawn.
=> Redo starting ToD stuff

SettingsList.py, data/World/Deku Tree MQ.json, data/World/Deku Tree.json, data/World/Forest Temple.json, data/World/Ganons Castle.json, data/World/Gerudo Training Grounds MQ.json, data/World/Gerudo Training Grounds.json, data/World/Overworld.json, data/World/Shadow Temple MQ.json, data/World/Shadow Temple.json, data/World/Water Temple MQ.json, data/World/Water Temple.json
Changes:
- Moved Invisible Walls trick toward the top of the list, as that's a pretty basic trick.
- Fixed some bugs involving an assumed Bow when going from GTG MQ Right Side to the Underwater Rupee Room.
Added Tricks:
- Zora's River Upper Freestanding PoH as Adult with Nothing
- Shadow Temple MQ Truth Spinner Gap with Longshot
- Lost Woods Adult GS without Bean
- Graveyard Freestanding PoH with Boomerang
- Death Mountain Trail Soil GS without Destroying Boulder
- Gerudo Training Grounds Left Side Silver Rupees without Hookshot
- Gerudo Training Grounds MQ Left Side Silver Rupees without Hookshot
- Reach Gerudo Training Grounds Fake Wall Ledge with Hover Boots
- Water Temple Cracked Wall Chest with No Additional Items
- Water Temple North Basement with Precise Jump
- Goron City Leftmost …
=> Another Batch of Tricks

Patches.py, SettingsList.py
Changes the fast chickens option to behave more like the big poe option:
- All chickens start in their normal positions instead of some of them being inside the pen
- Anju only wants the number of chickens specified by the slider (or a random number)
- Setting the slider to 0 will make Anju automatically give the player her item
- Edited Anju's text to tell the player how many chickens she wants
=> Upgraded fast chickens option

Patches.py
For some reason '-' operators were put at the beginning of a couple of lines defining the 'tod' dictionary, breaking the patching process when changing the time of day in the randomizer.
This just removes those '-' and fixes the problem.
=> Patching time of day fix

Hints.py
Fixes #761.
My rewrite of the line wrapping function seems to have caused the altar text to lose a bunch of box breaks. This adds them back in.
=> Fix Altar Text

EntranceShuffle.py
If both Closed Forest and Entrance Randomizer were chosen, it'd result in a NoneType error in set_entrance_updates.
=> Fix Closed Forest / ER

data/World/Spirit Temple MQ.json
This use of requiem in the spirit temple to assume child access breaks
both ER and adult start logic. Fix it.
=> Fix requiem use in MQ spirit logic

Patches.py, State.py, data/Glitched World/Overworld.json, data/World/Overworld.json
Changed gossip fairy logic to use another state method that checks if you can summon a gossip fairy without Sun's Song for places where playing Sun's Song reloads the room. 
The previous implementation checked for time passing instead, but some places like grottos and dungeons don't reload with Sun's Song even though they don't have time passing so it didn't work for all cases. 
This essentially fixes grotto and DC gossip stone fairies not being in logic with Sun's Song when they should have been.
Also fixed the gossip stone in vanilla DC to use a local flag instead of a permanent flag for the fairy spawn so it can be a reliable fairy source. All other gossip stones, including the one in MQ DC, use local flags, so only that one seems to have been a mistake in the original game.
=> Gossip Stone Fairy fixes

Patches.py
In cowsanity, moves the right cow in the stable one block away so its trigger area no longer overlaps with the other cow. This makes getting the items much more reliable as you can no longer mistake which cow you got the item from, and you don't have to place yourself in a specific spot to get one of the cows.
Fixes #665.
Before the change:
After the change:
=> Move the stable cows away from each other in cowsanity

RuleParser.py
This is a required argument in 3.8 but we can pass it in a keyword so it's ignored in < 3.8.
=> python3.8 beta compatibility: posonlyargs

ItemPool.py
If pending_junk_pool still contained items after all junk items were placed, the items in pending_junk_pool replace a random junk item. However, pending_junk_pool would retain those items for the next seed generation.
=> Ensure pending_junk_pool is emptied during generation.

data/World/Dodongos Cavern.json
This was assuming either bombs (for the entry stone) or master sword.
With weaponless child entry now possible it needs weapons checks.
=> fix scarecrow skull weapons check in ER

Entrance.py, EntranceShuffle.py, Location.py, Playthrough.py, RuleParser.py, State.py, data/Glitched World/Spirit Temple.json, data/World/Deku Tree.json
Big (ish) changes:
- There aren't any more recursive calls that involve changing age and testing can_reach again, so we can mostly remove the age parameter from `State.can_reach` and `State.with_age` can be split in two to be more efficient.
- There are a few cases where `current_spot` is still needed, so we can't quite remove `with_spot` yet, but we can remove a few extra lambda declarations by having a separate `can_reach_simple`.
- We don't actually need to pop things out of the entrance queue!
=> Minor speed improvements to playthrough algorithm

EntranceShuffle.py, Fill.py, Main.py
I added a common type of exception called `ShuffleError`, currently only extended by `FillError` and `EntranceShuffleError`, corresponding to errors likely due to randomisation fails on which the global retry should trigger.
Previously only `FillError` exceptions were caught by the global retry which didn't handle the ER algorithm fails since it uses `EntranceShuffleError`.
=> Fix entrance shuffle fails not being caught by the global retry

SettingsList.py, data/settings_mapping.json
The main focus of this is to get the detailed logic tab content
consistent, although there are a few other tweaks in here too.
Starting with detailed logic, im going for the following definition
of what belongs on the tab:
1: If it has any impact to no-logic gameplay it should not not be on
this tab.
2: If it has no impact whatsoever to no-logic gameplay it should be
on this tab.
The is because this tab greys out in entirety depending on whether
no-logic is selected or now.
This leads to the following changes:
The trade sequence clams should be booted off the tab as they do impact
no-logic gameplay. It makes sense to move to 'other' considing it is
a minor setting (affecting one check). The 'Misc' column is getting
long so buddy these two up with the Ice Traps and Item Pool to make a …
=> Gui options tweaks

RuleParser.py, State.py
py3.8 is broken due to an AST change where Str is treated as Constant, meaning the visit_Str is not called appropriately.
=> python3.8 compatibility: Str vs Constant

GUI/src/app/pages/generator/generator.component.html, GUI/src/app/pages/generator/generator.component.scss, GUI/src/app/pages/generator/generator.component.ts, SettingsList.py, data/settings_mapping.json
Adds separate inner/outer color options for Navi and place them on the same line if the GUI window size is big enough (4/12 column layout). With this Electron can now handle no_line_break for a ComboBox as well.
What's missing from this PR is the python source adjustment to properly handle the new separate color options on generation instead of looking for 2 hex colors in one setting.
=> Add Navi inner/outer separate cosmetics options back

Cosmetics.py, Music.py, SettingsList.py, data/Music/README.md, data/settings_mapping.json
Adds an option similar to Background Music shuffle/disable, except for the short, non-looping fanfares. Includes the ability to load user sequences. Also adds a toggle (hidden unless fanfares are shuffled or disabled) for adding ocarina songs to the fanfare pool. Also expanded the music readme a bit.
=> Add fanfare shuffle

SettingsList.py
- Changed the "Shuffle Weird Egg" tooltip in accordance with the fact that "Open Kakariko Gate" no longer exists.
- Added missing periods in certain tooltips.
- Fixed "Ganon's Boss Keys" setting name to "Ganon's Boss Key" (singular).
=> Minor settings fixes in names and tooltips

Patches.py, SettingsList.py, State.py, World.py, data/World/Overworld.json
Along with trade timers being disabled, items will now never revert in ER when interior or overworld entrances are shuffled ("Simple Indoors" and higher settings). This is done to avoid inconsistencies with logic not being able to account for the fact that save warping can't be used to deliver items.
Previously, logic would arbitrarily require certain songs to ensure you can reach adult's save warp which is the starting point for logic. But this wasn't ideal, especially when ToT or overworld entrances were shuffled, in which case Prelude was hard required to complete the trade sequence logically, even when it wasn't needed at all gameplay-wise.
With items not reverting under those circumstances, I had to rewrite the glitchless trade quest logic. 
I decided to split the different trade …
=> Prevent trade items from reverting on save load in certain ER settings

EntranceShuffle.py
Some changes and fixes to the special checks run while shuffling entrances:
- Removed the hard restriction for Temple of Time not being at the Fishing Pond entrance since that was intended to prevent potential issues with child lake control which is no longer a thing.
- Added a check to guarantee access to the Big Poe Shop as adult so players can never be locked by filling their bottles with Big Poes when they don't have access to the place where they can get rid of them. I had intended to handle that a long time ago but had forgotten about it until recently..
- Made it so all validation checks are run once before confirming the placement of every entrance pool. This is meant to catch problems earlier so the local retry can be used if something went wrong when shuffling a specific …
=> Minor ER validation changes and fixes

SettingsList.py, data/settings_mapping.json
Simplify the cosmetics page to be a similar layout to the other pages.
This had too many micro-sections with only a few headings that have
little scope for future expansion.
Wrangle all sword, tunic and gauntlet settings under 'equipment'.
Move the 'general' pieces to the headline as these are more about
functionality and gameplay rather than cosmetic. For these reason,
they should be exempt from randomization so put them alongside the
new randomization setting in the headline.
Music and SFX has a headline with a randomize all toggle.
=> Cosmetics page simplification and randomized cosmetics

data/World/Dodongos Cavern MQ.json, data/World/Overworld.json, data/World/Spirit Temple MQ.json
Fix the first batch of logic issues identified in detailed review of the logic by r0b.
commit d900e00e6c3019bd97f166f376d0fae0a8c9052b (HEAD -> settings, rattus/logic-audit-1)
Author: rattus128 <rattus128@gmail.com>
Date:   Tue Jul 30 14:42:24 2019 +1000
Add collossus exit MQ Spirit
Its almost the same as the silvers chest, however you must check for
adult on the 4 key route and only let adult escape on that route to
avoid an unknown age issue in the colossus.
commit 97361e544b2a3cf84bda5184e51e3df71e283358
Author: rattus128 <rattus128@gmail.com>
Date:   Tue Jul 30 14:35:11 2019 +1000
Fix spirit MQ hallway logic
This needs to be an at() rather than a here. The here(is_adult and ...)
was self contradictory, as this region is only ever reachable as child,
placing the fire arrows route …
=> Logic fixes - set 1 (audit in progress - there will be more)

EntranceShuffle.py, Fill.py, Hints.py, Main.py, Playthrough.py, Rules.py, State.py
Now fixes #811 by ensuring Playthrough always copies, but this had a strange interaction with how location hints modify the locations they're hinting at, possibly due to a couple latent bugs, including testing for adult access to child-only stones which kills the logic. Fixed that by using `Playthrough.can_reach` as child only, instead of `State.can_reach` at whatever age being tested.
=> Copy state before generating WoTH. (Fixes #811)

Patches.py, data/Glitched World/Spirit Temple.json
Change the logic for Twinrova Heart and Medallion to be correct.
Moved the Silver Gauntlets Chest to the right a tad when it's small so that it's possible to do Spirit Hover still.
=> Glitched Tweaks

Patches.py, SettingsList.py
Changed the patch used to prevent trade reverts to override the "trade revert table" item IDs so all reverts no longer work, no matter which part of the game code triggers them.
This should ensure trade items never revert back to a previous item, which is now the expected behavior in ER settings where the adult trade quest is affected.
=> Fix trade items still reverting on death in ER

Music.py
Ocarina Songs were added to the static list of fanfares causing duplicates to appear in the list and fail the assertion that there will only ever be one copy of a fanfare at any time in successive generations using the Generation Count feature.
A new list is now created and is extended to add both fanfares and ocarina songs to the new list and then operate on that new list instead of the static ones.
=> Fix Ocarina Songs as Fanfares on successive generations

ItemPool.py, LocationList.py, data/World/Bottom of the Well MQ.json, data/World/Dodongos Cavern MQ.json, data/World/Fire Temple MQ.json, data/World/Forest Temple MQ.json, data/World/Ganons Castle MQ.json, data/World/Ice Cavern MQ.json, data/World/Jabu Jabus Belly MQ.json, data/World/Overworld.json, data/World/Shadow Temple MQ.json, data/World/Spirit Temple MQ.json, data/World/Water Temple MQ.json, data/World/Water Temple.json
Fixing these drop locations seemed somewhat different from the rest of the logic changes I'm planning to make? So I made this a separate PR.
Added these drop locations:
- BotW MQ (Explosives + Slingshot - Fairy Pot)
- Ganon's MQ (Scrubs room - Free Fairies; Spirit Trial end - Nut Pot)
- Water MQ (Longhost + 1 key - Fairy Pot; Longshot + 1 key - Nut Pot)
- Forest MQ (Behind SoT block - Fairy Pot)
- Fire MQ (Behind lower right door - Fairy Pot; Boss Key Chest room - Fairy Pot; East Tower Climb - Wall Switch Fairy; Flame wall Maze - Fairy Pot; further fairies logically irrelevant)
- Shadow MQ (Room before boat - Nut Pot)
- Ice MQ (2nd Room - Fairy Pot)
- DC MQ (Boss Area - Fairy Pot)
- Spirit MQ (Child side, after Bombchu, sling, and sword/stick requirement - Fairy Pot)
- Jabu MQ (Pre boss …
=> Add Drop Locations

Main.py, Playthrough.py
The Playthrough only needs to be rewindable for generating the seed playthrough, and not for seed generation nor even for determining beatability. This accounts for >90% of the memory previously used. We can also eliminate the sphere indexes, which aren't truly necessary.
Restructuring like this is also a minor speed improvement!
Some multiworld generation memory stats:
- 15: ~120 MB
- 25: ~280 MB
- 50: ~1 GB
=> Reduce over-aggressive caching

Fill.py, World.py
I hate making PRs fixing my previous PRs but I botched the heck out of this. Now it should work.
Default shop items (e.g. tunics and Buy Blue Fire) aren't classed as major items, so we should check for advancement items instead. Also fixed a really dumb mistake in the if/else because boolean logic is hard.
=> Fix Maximum Wallet Logic

EntranceShuffle.py, SettingsList.py, data/World/Deku Tree MQ.json, data/World/Fire Temple MQ.json, data/World/Forest Temple MQ.json, data/World/Forest Temple.json, data/World/Jabu Jabus Belly MQ.json, data/World/Jabu Jabus Belly.json, data/World/Overworld.json, data/World/Shadow Temple MQ.json, data/World/Water Temple MQ.json, data/World/Water Temple.json
Changes:
- Added note to BotW Cage GS without Boomerang, that you can obtain the token prior to being dealt damage by the Like Like.
- Added note to Water Longshot Torch trick that the majority of the Iron Boots skips in Water Temple are not relevant unless you first enable it.
- Renamed "Adult Meadow Access without Saria's or Minuet" to "Backflip over Mido as Adult", since now with ER, it's not likely going to be the Meadow that you access early.
- Renamed Death Mountain Trail Lower Red Rock GS without Hammer to "with Hookshot" to account for the Magic Bean method.
- Renamed "Climb Fire Temple..." trick to "Fire Temple Climb..." just because.
- I arbitrarily reordered the items in the trick list again...
Bug Fixes / Logic Changes:
- The torch that spawns Deku Tree MQ Slingshot Room Back …
=> "Final" Final Logic & Trick Update

Main.py, Rom.py, ntype.py
Most of the improvement comes from finding places where we call a python function for every byte/int32.
- Fixes the error in making a patch file.
- Writes multiple bytes to the buffer at once, instead of one at a time.
- Changes crc calculation to start by reading the whole block and dividing into chunks, instead of reading each chunk separately.
- Delays some bitwise-ands used for truncation. (Verified the crc still computed the same via a visual test.)
=> Speed up some bytes-processing issues

Entrance.py, EntranceShuffle.py, Fill.py, Location.py, Playthrough.py, Region.py, RuleParser.py, State.py, World.py
The graph algorithm behind playthrough works for ToD as well, just with the caveat that we don't want to do it all the time, due to the low rate of ToD checks. But we can do the following:
1.  Make the region sets actually dictionaries, with available times of day as the value. Presence in the dictionary means the same thing as it did before for the set, but now when we reach a new region, we add its natural available times.
1.  When we need to know if a ToD is available in a region, we start with the regions in its world that have the appropriate time, and expand outward until we reach the target region or run out of exits.
1.  For space reasons, we use an enum value. For performance reasons, the enum is actually just raw integers.
(Theoretically, we could also provide the ToD we lazily …
=> Move time-of-day checking into Playthrough

Entrance.py, Item.py, Location.py, Main.py, Region.py, RuleParser.py, World.py
Allows checking if a location is internal, more simply than checking if it has an item name in item_table.
Also removes another unused attribute.
=> Add 'internal' marker to internal Locations.

EntranceShuffle.py
Since Impa's House entrances are considered simple interior entrances, the cow check has to be run even if special interiors aren't shuffled.
=> Fix Impas House Cow check in ER to work properly in Simple Indoors

Entrance.py, EntranceShuffle.py, Hints.py, Location.py, Main.py, Playthrough.py, Region.py, Rules.py, State.py
It is done.
----
Mostly cleanup without behavior changes.
*  An ER check is improved to take into account Playthrough ToD behavior, and its playthrough deduplicated.
*  `Playthrough.can_reach` is the only `can_reach` function remaining.
*  A bunch of functions that just passed their arguments on were removed, for a small gain in performance.
*  In total, ~10% performance improvement.
=> Remove State.can_reach

GUI/src/app/@theme/styles/styles.scss, GUI/src/app/components/guiListbox/guiListbox.scss, GUI/src/app/pages/generator/generator.component.scss, data/settings_mapping.json
- All button-like elements now have a "pointer" cursor on hover to emphasize they can be interacted with (better for UX and also what is generally done for all buttons). They also no longer have an outline when on focus. Their color already changes in that situation so the outline just looks a bit weird for no real gain. This applies to all buttons on the UI as well as all dropdowns.
- Scrollbars are now a bit thicker, based on how much they should stand out. They also now all use the same blue-ish color to keep the UI consistent and differentiate them from the many other UI elements using the exact same green as the main scrollbar used.
- Row spans are adjusted for each tab to prevent the top section from taking more space than required, which saves space for the rest of the sections …
=> Some GUI style tweaks for UX and consistency

ItemPool.py, SettingsList.py
Adds an "Overworld Only" option to Tokensanity, shuffling the opposite set of skulltulas from "Dungeons Only".
=> Tokensanity: Overworld Only

Patches.py, SettingsList.py, data/settings_mapping.json
I know this topic is quite controversial but it's also heavily wanted so I'm suggesting a compromise by adding it as a time-saver option.
Basically what this option does is allowing you to get both rewards at once if you complete dampe's race in under a minute the first time. Of course, if you complete the race in over a minute, you are still able to get the first chest reward as usual but you still won't receive the second reward until you manage to complete a race in under a minute.
It doesn't remove any difficulty and the checks require the same amount of skill but it's a good time-saver for players who are good enough to complete it in less than a minute on their first try.
The patch for this option is also very simple since it's just setting the "Beat First Dampe Race" clear flag.
=> "Skip First Dampe Race" Convenience Option

Patches.py
This fixes a pretty minor but quite annoying issue from the vanilla game with some of the Great Fairy entrances having an interactable textbox (triggered if you roll nearby) even after you opened the way to the entrance.
More specifically, the Child Colossus Fairy one is fixed to use the proper flag so it actually goes away after you destroyed the wall (seems to have been an oversight from the original oot devs). And the Crater Fairy one is just completely removed because there are 2 bronze boulders at that entrance which use different flags so there is no way to bind it to any of the 2 boulders being destroyed.
=> Fix "...???" textboxes at the entrance of Great Fairies

SettingsList.py
- Fixed the "Disabled Locations" tooltip to properly reflect that those locations now only hold junk items instead of items not required to beat the game. Fixes #879.
- Made the "Ganon's Boss Key" setting a bit more consistent with other key settings (in the order and naming of options).
- Fixed the "All Locations Reachable" tooltip to no longer mention that key-for-key situations are possible since it hasn't been the case for a long time now.
- Updated the "Dungeons Have One Major Item" tooltip when it comes to the circumstances in which some items count as major item (keys, GS tokens and bombchus).
=> Minor Setting Fixes

SettingsList.py, data/World/Overworld.json
Fixes #888.
Also added a mention in the trick tooltip that fall damage is unavoidable.
=> Fix logic for the Valley Crate PoH with hovers trick in OHKO

RuleParser.py
If you put something not an AST in an AST, you wind up with a complaint about missing lineno instead of an error pointing out the problem. This exception catching makes it a little easier to debug.
=> Fix item coalescing, emit better error messages

Hints.py
In case the distribution has to fill remaining gossip stones with extra hints (eg. if there aren't enough woth or barren areas), it will now first use duplicated sometimes hints, and only fall back to random location hints if necessary.
And in the rare occasion where random location hints end up being used as fallback, they will now also be duplicated like everything else in the tournament hint distribution. I think this can only happen if the player disables many locations targeted by sometimes hints, but it's definitely possible.
=> Fix tournament hint distribution to correctly fill extra hints

SettingsList.py
- Reworded the token option to `"A configurable amount of Gold Skulltula Tokens"` in the bridge requirement tooltip, to make it clear that you can now configure the amount required.
- Improved the formatting of some tooltips to better fit the new GUI tooltip sizes.
- Fixed all dropdown tooltips to use a consistent format with all options described with the syntax `'Option': <description>` which most tooltips were already using (but not all).
=> More Minor Tooltip Tweaks

HintList.py, Rules.py, World.py, data/Glitched World/Overworld.json, data/World/Overworld.json
Currently, the only instances of conditionally required hints are: 10 Big Poes which is only required if more than 3 poes are needed for the check, and Skull Mask which is only required in Tournament distribution.
This PR adds the same kind of flexibility to other hints such as OoT locations for example, which only need to be required when getting Spiritual Stones is out of the usual way to complete the seed. So if the Rainbow Bridge is set to "All stones" or "All dungeons" instead of the usual "All medallions", it should be a hint that only shows up sometimes instead of being hard-required.
Similarly, the "Sheik at Kakariko" location should be a required hint in settings where you may not need to collect the Forest, Fire and Water medallions in order to complete the seed, in which case …
=> Make more hints conditionally required based on settings

ItemPool.py, LocationList.py
The data for the Shadow MQ map and early gibdos chest was backwards.  Vanilla settings were swapping their contents as was plando.  This resolves both issues.
=> Resolve issue #924

SettingsList.py
For the `Starting Time of Day` setting, the time is now indicated in all available options. For example the default option now says "Default (10:00)" instead of just "Default".
=> Add the corresponding time in Starting Time of Day options (QoL change)

EntranceShuffle.py
The indentation was wrong so the special hint area check was only running for the last world instead of every world...
=> Fix the ER cowsanity check for Impa's House Cow in multiworld

Plandomizer.py
While `pool_remove_item` takes an iterable of pools, `pool_add_item` takes a single pool. Somewhere in `alter_pool`, it's currently passed a list of pools.
=> Fix a bug in Plandomizer.WorldDistribution.alter_pool

Settings.py, SettingsList.py
This fixes the 'Randomize Main Rules' setting.
This includes Triforce Hunt as a randomized setting and disables it while the randomize main rule settings switch is on.
As a note, if randomized main rules triggers Triforce Hunt to be enabled, it will only take the default of 20 triforce pieces. This was left as is because using the min and max of 1 and 100 would sometimes prevent the rom from successfully generating due to lack of item space left over.
=> Issue908: Fix for randomized main rules

Cosmetics.py
Simply added patches to have File Select hearts match the Ingame UI heart colors when using the corresponding cosmetic option.
=> Improve Cosmetic Heart Colors to apply in the File Select screen

Item.py, Location.py, Main.py, Playthrough.py, RuleParser.py, World.py
* Grabbing a locations list only involves a single iteration.
* Replace an internal function call.
* Cache generated rule functions.
Approximate 17% speed-up total on non-fuzzer unittests.
=> Minor generation speedups

SettingsList.py, Unittest.py, tests/ac-mq.sav, tests/accessible.sav, tests/disables.sav, tests/entrance.sav, tests/entrance2.sav, tests/glitched-standard.sav, tests/multiworld.sav, tests/nightforest.sav, tests/triforce-multiworld.sav, tests/triforce.sav
* Don't include a separate value for `trials` in both the settings and the randomized settings when `trials_random` is on.
* Use the same seed for non-fuzz unittests.
=> Minor fixes

SettingsList.py
Fixes #955 among other typos.
Grammatical errors and inconsistencies are not touched except one in Basement Webs with Bow.
=> Various typo fixes

Hints.py
By choosing the additional entries from `duplicates` first in this way, the randomness is much better preserved: you can envision the process of hint selection like so:
1. Shuffle the list of stones.
1. The first reachable stone gets a copy of the hint.
1. The first stone that isn't the one above gets the other copy. (This step used to be more like "The first stone *after* the one above gets the other copy.")
So now, given the identity of the first reachable stone, it should be equally likely among eligible remaining stones which one is the duplicate. Previously, it was *less likely* that a stone locked by a hinted item would have the duplicate of that item hint. (Doing some math, the worst case might be 50% less likely than it should be.)
I believe correcting this will slightly increase …
=> Hints: select duplicate from unreachable locations if necessary

Hints.py, LocationList.py, Main.py, README.md, data/Glitched World/Overworld.json, data/World/Overworld.json
This makes it so you won't see a Way of the Hero (or a sometimes hint) pointing directly to the Light Arrows location specifically if Ganondorf is reachable logically without Light Arrows. Any items that are only needed for Light Arrows are still fair game to be hinted, of course. This just makes hint logic consider that Ganondorf as a hint.
=> Consider Light Arrows location hinted if Ganondorf hint can be reached.

data/LogicHelpers.json
This seems to have been missed in a merge conflict a while ago when TH was merged.
=> Fix the logic check for custom token bridge requirements

GUI/electron/src/modules/generator.js, GUI/src/app/pages/generator/generator.component.ts, README.md
Allows spaces and other characters to be used in seeds again without causing errors.
Should avoid other errors that could be caused by entering strange data into the seed field.
Hopefully this is something @dragonbane0 and @TreZc0 are good with since I'm not really a JavaScript guy. This seems like the best solution to me but I'm not sure.
=> Stringify the seed before using it in the OoTRandomizer.py call

SaveContext.py
Ensure equipped value is not greater than 3
Ensure bgs_hits_left is non-zero when starting with Biggoron Sword
I was unable to get Goron Tunic to equip properly. It would only equip either Kokiri Tunic or Zora Tunic. For now I set it to always equip Kokiri Tunic.
Should fix #874. If anyone wants to take a crack at fixing tunics fully, please do.
=> Fix adult starting_items equipment

ItemPool.py, Plandomizer.py
When using the invert pattern in plandomizer (`!Bow`) on a non-song location and with songsanity off ignore the song item pool when choosing the item to place. It should only do this if a pattern is used to avoid placing an item the user did not intend.
Prior to this change trying to generate 100 seeds with an invert pattern would cause an error due to trying to place a song on a chest location part way through. After this change I could generate over 200 without issues.
The same is done for songs as a user using an invert pattern with songsanity off likely doesn't want to place an item on the song location, and would cause an error anyway since the pool is not modified to remove a song.
Not sure if it is needed for dungeon items being placed with any settings as I haven't run into it …
=> Plando: Fix placing various items on invalid locations

Plandomizer.py, README.md
Used this plando as a test
```json
{
"locations":
{
"Mido Chest Top Left":                                   {"item": ["Bow", "Light Arrows", "Magic Meter"]},
"Mido Chest Top Right":                                  {"item": ["Bow", "Light Arrows", "Magic Meter"]},
"Mido Chest Bottom Left":                                {"item": ["Bow", "Light Arrows", "Magic Meter"]},
"Mido Chest Bottom Right":                               {"item": ["Bow", "Light Arrows", "Magic Meter"]},
"Skull Kid":                                             {"item": ["Bow", "Light Arrows", "Magic Meter"]},
"Ocarina Memory Game":                                   {"item": ["Bow", "Light Arrows", "Magic Meter"]},
"Target in Woods":                                       {"item": ["Bow", "Light Arrows", "Magic Meter"]} …
```
=> Possible plando lists fix/implementation

Plandomizer.py
This PR should ensure that you cannot place more than 3 bottles in `closed_fountain` and 4 bottles in `open_fountain` along with disallowing duplicate adult trade items.
As a bonus of implementing this to a degree I'm happy with I think I ended up solving the issue where `item_pool` doesn't update when adding more items than the given `item_pool`. This may be undesired for custom item_pool definitions, in which I can raise an error on if desired. However I believe most users expect it to work this way when using the default base pool at the very least.
-----
ToxicOxygen on the Discord brought up the fact that `starting_items` should work similarly. As such, starting items will now remove from the item_pool too and be replaced with junk. Examples of this for normal items:
- Starting items …
=> Avoid Exceeding 4 Bottles and 1 Trade Item; Properly Update Item Pool Automatically

Plandomizer.py
Looks like I made pattern_dict_item attempt to use an attribute of an object that may not exist without properly checking for it.
I don't think this is a major issue for starting_items in plandos so I didn't revert the change that removed the pattern_dict_items usage, though I may choose to later as maybe patterns in starting_items would be neat, but for now this fix is necessary as this issue breaks other things such as custom gossip stone text in plandos.
=> Fix pattern_dict_item

ItemPool.py, Plandomizer.py
The new starting_items changes automatically remove the items from the item pool which broke the start_with_fast_travel and start_with_wallet options as they also remove from the pool.
This first cuts out the removal of the items from the pool from ItemPool.py as it is now automatic.
Second, most items other than bottles or trade quest items should be fine to exceed the item pool amount, so in Plandomizer.py, remove them until the item pool runs out, then ignore the fact you are adding more than are available.
This should fix the "start with" options.
=> Plando: Fix "start with" options

Main.py, OoTRandomizer.py, SettingsList.py
This Pull Request: 
- Cleans up some unused imports
`Main.py:`
- Removes the unused worlds array in Main.py
- Moves the settings.compress_rom check from out of under the player_num check, to above it.
- Snaps the player_num down to world_count if it's > world_count
`OoTRandomizer.py` 
- Removes the unused/uncalled Gui section
- Removes the variable assignment from check_version - that func doesn't return anything.
`SettingsList.py`
- Stripped some trailing spaces (I can revert this if it's annoying)
- Add clarifying statements to `disabled_locations` and `allowed_tricks`
- Disable the tricks menu, when glitchless is chosen, because glitched logic doesn't take into account the 'Enabled Tricks' settings at all, and would be confusing for users.
=> Minor text fixes

Location.py, Plandomizer.py
People often make case mistakes when using location names. i.e: "Gift From Saria" instead of the proper location name "Gift from Saria"
This change should match location names case insensitively but still use the proper case the location actually uses.
=> Plando: case-insensitive location matching

Plandomizer.py
If Letter has not been shown to guard before obtaining a second weird egg a softlock can occur if there are important items at deku theater or an important location locked behind the gate or if Keaton Mask gets overwritten before giving it to the guard.
=> Plando: Only allow one Weird Egg in the world

SettingsList.py
Copy-paste mistakes were made.
=> Fix gauntlet colors tooltips to not mention rainbow sword trails

Plandomizer.py, Unittest.py
Tried using this to test file_hash when writing the plandomizer wiki page and it didn't work. Turns out I didn't properly update the file path for this test when I moved all the plando test distribution files into their subdirectory.
=> Fix ammo bounds test not using plando file, and defined bottles

SettingsList.py
This reverts commit ee9e091a6f14123e67117e293838b73d6b200377 so that the tooltip matches the restoration of Ice Trap looks-like items affecting Chest Size Matches Contents.
=> Fix "Ice Trap Appearance" Tooltip

.gitignore, Entrance.py, Location.py, Main.py, RuleParser.py, Search.py, State.py, World.py
(and typo fixes)
- Cache per-world which 'won' metric to use.
- Move static State method `update_required_items` to Main, the only place it's used, so we can reference State in Search more easily. Remove `State.can_beat_game` entirely.
- After parsing and condensing rules based on settings, drop entrances that can't be used, events that can't be reached, etc. Mark always-true locations, but only use this for simplifying rules added later (hint access, wallet size for shops, etc).
- Minor code changes to Search alg that had small boosts to perf.
- Fix a typo affecting rule parsing.
- Fix a typo in the .gitignore and add a few more things to it.
These changes result in a ~1-2% speedup for 5-player and 20-player multiworlds.
=> Minor performance improvements

Main.py, World.py
Mainly, determine the largest Skulltula token check per-world
and set that as the limit.
This results in a ~6-7% performance improvement for a 5-world seed,
and negligible difference for a 1-world shuffle-tokens seed.
(We could obviously do even better by checking what's *placed* at those
locations, but this will do for now.)
=> Lower progression limits for item requirements.

Cosmetics.py, ItemPool.py, Messages.py, Sounds.py
A few assorted, small changes.
1. Added a "mweep" at the end of King Zora's dialogue when showing him the letter. Since the cutscene is gone, I feel like this is a nice replacement for it.
2. Re-added "Child Scream" to Menu Select SFX. Menu Selection isn't something that needs ear-safe sounds and this one works well in that spot.
3. Triforce Hunt now rounds the amount of pieces per world instead of simply dropping the decimal entirely. This is helpful when using a low number of triforce pieces required and makes more sense overall.
4. dotzo's weirdshot fix on glitched or no logic from #854. This was lost to a rebase but was intended to get merged, I yanked it back out of the void.
=> Assorted Minor Changes

OoTRandomizer.py
Set a non-zero error code after printing a caught exception to the logger.
I often use [a shell script](https://pastebin.com/raw/01NuYPCm) to generate seeds until one works, which can often be necessary when testing a plando. However it relies on the output of a failed attempt to be a failure code and a successful one to be 0 so that it can stop after finding the working one.
Currently the randomizer always returns a 0 success exit code even on failure. This PR returns an 1 error exit code instead.
=> Set error code after failure

Main.py, Plandomizer.py, Settings.py
I set the retry to 10, don't know if that's high or not. I still see fuzzer seeds that fail even that many attempts.
---
Because the distribution is used for spoiler output, when we generate
the item pool, we save it in the distribution. This is a problem when
retrying, because we generate a new item pool, and this could have more
shop items in it than shop locations.
So, to fix that, we split the Distribution update method (only ever
called on init) into once-only init and once-per-retry reset. This was
already clearing the WorldDistributions to start with.
And then remember to forward disabled locations back into the distribution.
=> Fix and reenable global retry

Main.py, Plandomizer.py, Settings.py
This is a simple commit that creates a copy of the distribution file used in the output folder using the same naming conventions as the spoiler and cosmetic logs.
=> Copy distribution file to output when using a distribution file.

data/presets_default.json
small edit to scrubs setting preset - removes the trick "logic_lens_shadow_back" to require lens for logic for the back half of shadow temple (invisible platform and beyond)
=> editing lens logic for scrubs settings

data/World/Overworld.json
This bug appears to be an oversight from the spoiler log cleanup (#1021).
Fixes #1056 and probably #1053.
=> Fix Hyrule Castle Grounds logic not using the right entrance

Music.py, SettingsList.py
This was posted in the suggestions channel and was a feature I also wanted. It was easy to do so I figured I would do it =)
Add a new option for Background Music: Randomize (Custom Only)
- Do not shuffle any of the base Ocarina of Time music into the game.
- If not enough custom music sequences are provided, raise an exception stating such.
I also added this features for fanfares as well.
=> Add a new option for random music while omitting vanilla OoT music

data/Glitched World/Spirit Temple.json
It expected child link to be able to use mirror shield.
=> Fixed an oversight in glitched spirit logic

SettingsList.py
Fixes #1052
When generating settings strings, list settings such as the Starting Inventory Items use [0...0] and [1...1] as special terminating values. However, this was not accounted for in the bitwidth of the setting, resulting in errors for settings with exactly 2^n or 2^n-1 choices, for any n. This fixes the issue by explicitly considering the special terminators when calculating the bitwidth, adding an extra bit only when needed.
=> Ensure settings lists have enough bitwidth

Cosmetics.py, ItemPool.py
Currently it only shows the random music in the cosmetics log if one of music/fanfares is set to the normal "Random" setting.
Default behavior for Python when rounding a .5 is to round it to the next even number (up or down) instead of always rounding up to the next whole number.
Example, previously a goal of 3 pieces on Balanced item pool (4.5 pieces) would result in 4 pieces in the pool. Now it would result in 5.
=> Assorted Fixes

HintList.py
Fixes #1067. Hint was incorrectly pointing to Colossus Deku Scrub Grotto Front for some reason.
=> Fix DMC Deku Scrub Hint

HintList.py
Not good for intercommunity relationships, not justified anymore with PJ64 improving massively and being considered for races.
=> Remove PJ64 Junk hint

Messages.py
Fixes #1070. Long text chains here can make the Cow in House obstacle course difficult or impossible to complete.
=> Text Shuffle: Exempt "One more lap!" from being shuffled.

Fill.py, ItemPool.py, Patches.py, Plandomizer.py, Rules.py, SettingsList.py, data/settings_mapping.json, tests/ac-mq.sav, tests/accessible.sav, tests/disables.sav, tests/entrance.sav, tests/entrance2.sav, tests/entrance3.sav, tests/glitched-standard.sav, tests/glitched-tokens.sav, tests/multiworld.sav, tests/nightforest.sav, tests/plentiful.sav, tests/tokensanity.sav, tests/triforce-multiworld.sav, tests/triforce-startingitems.sav, tests/triforce.sav
Songs will only appear at the boss heart contains in major dungeons, or at final reward in minor dungeons. Because this is still short 1 location, the ZL location is added as the final 12th. The idea is for it to pair with the potential option in the future to start with the ZL location.
=> Add option to shuffle songs in dungeon reward locations

Plandomizer.py
The plando file
```
"starting_items": [
"lens",
"hammer"
]
```
produced the error
```
KeyError: 'invalid starting item: Lens of Truth'
```
when the actual problem was that "hammer" should be "megaton_hammer".
This change fixes the error to
```
KeyError: 'invalid starting item: hammer'
```
=> Fix plandomizer itemsetting error message

SettingsList.py
This updates the tooltip copy for the open_forest setting to more
accurately describe what happens in the closed_forest setting.
Specifically, it mentions what is blocked and what happens if you use
incompatible settings.
Fixes #910
=> Clarify closed_forest tooltip

Goals.py, Search.py, World.py
MW seeds with random trials on can fail to generate if the trials enabled in World 1 are not enabled in other worlds. The system also failed if one world has no trials as the trials category key does not exist during goal/woth calculations. This should also affect a fixed number of trials on in MW as which trials are enabled is still random.
Goal hints do NOT need to be active for the failure to occur. This PR is recommended as a hotfix for 6.1.
=> Fix multiworld random trials interaction

Fill.py, Goals.py, Location.py, Search.py, SettingsList.py, State.py
**Edit:** [See this comment for the new fix.](https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1441#issuecomment-973643433)
Updates the fill code to ensure that once it has started to do access checks, it will keep doing them for the rest of the fill. This seems to fix the generation failure with this plando:
```json
{
"settings": {
"reachable_locations": "goals",
"bridge_medallions": 4,
"shuffle_ganon_bosskey": "vanilla"
}
}
```
It should also be a minor seed generation speed-up in AGR and RO since it won't do extra `can_beat_game` checks anymore to determine whether to do access checks if it's already doing access checks.
=> Fix AGR generation errors by making it work more like RO

SettingsList.py
This PR changes the name of the Enable Useful Cutscenes setting to Enable Specific Glitch-Useful Cutscenes to more clearly define what the setting does. Also removes outdated reference in tooltip to the Twinrova cutscene, which is now default, and specifies that the setting is only a time saver when playing with glitchless.
=> Change name of Enable Useful Cutscenes setting to Enable Specific Glitch-Useful Cutscenes and tooltip update

Hints.py
Maintain two separate lists of checked locations, one with the Always-hinted locations and the other with everything else. Foolish hints only check the latter list, while all other hint types check both. This lets foolish hints share areas with always hints, but not sometimes hints.
=> Allow foolish hints for areas with always hints but not other hint types

LocationList.py
Fixes the issue shown below, "Talon's Chickens" incorrectly being a "Kakariko" check and "Outside Ganon's Castle" being at the bottom of the list.
=> Minor location categories fixes
